# Ch12 예외
## 예외
프로그래머가 생각하는 시나리오에서 벗어나는 사건을 예외(Exception)이라 한다.<br/>
예외가 프로그램의 오류나 다운으로 이어지지 않게 처리하는 것을 예외 처리(Exception Handling)이라 한다.<br/>

Main 함수에서 예외를 처리하지 않는 경우, 예외는 CLR로 옮겨지고 CLR까지 전달된 예외는 처리되지 않은 예외가 된다.<br/>
CLR은 예외 객체에 담긴 내용을 사용자에게 출력한 후 프로그램을 강제 종료한다.<br/>
프로그램은 예외를 처리하지 못해 종료되는 프로그램은 아무리 기능이 많아도 신뢰할 수 없다.<br/>
프로그래머는 자신이 작성한 코드 내에서 예외가 처리되도록 조치를 취해야 한다.<br/>


## try ~ catch
C#에서 예외를 받을 때 try ~ catch 구문을 이용한다. 형식은 다음과 같다.<br/>


	try
	{
	
	    // 예외를 감지할 코드 영역
	}
	catch ( 예외_객체_1 )
	{
	
	    // 예외_객체_1을 감지한 경우 실행하는 코드 영역
	}
	catch ( 예외_객체_2 )
	{
	
	    // 예외_객체_2를 감지한 경우 실행하는 코드 영역
	}


try 절의 코드 블록에서는 예외를 감지하는 코드 블록이다.<br/>
try 절에서 예외가 발생하면 catch 구문에서 예외 객체와 같은지 확인한다.<br/>
catch의 예외 객체와 try에서 발생한 예외 객체가 같은 경우 해당 catch 코드 영역이 실행된다.<br/>
만약 해당 catch 에 일치 하는 예외객체가 없는 경우, 처리되지 않은 예외로 남게 된다.<br/>
처리되지 않은 예외는 상위 경로로 올라가면서 계속해서 검증하고 앞에서 적었다 싶이 CLR까지 올라간다.<br/>


## System.Exception
모든 예외 객체는 System.Exception 클래스를 상속 받는다. 그래서 Exception으로 catch를 할 수 있다.<br/>
하지만 Exception은 프로그래머가 발생할 것으로 계산한 예외 말고도 다른 예외까지 받아낼 수 있다.<br/>
그 예외가 상위 코드에서 처리할 예외라면 이 코드는 버그를 만들고 있는 셈이다.<br/>
System.Exception 객체를 이용할 때는 코드를 면밀히 검토해야 한다.<br/>


## 예외 던지기
예외를 던지는 방법은 throw 키워드를 이용해 던질 수 있다.<br/>
C# 7.0부터는 throw를 문(Statement)로 사용했던걸 식(Expression)으로도 이용할 수 있다.<br/>


	int? val1 = null;
	int num1 = val1 ?? throw new ArgumentNullException();
	
	int val2 = 0;
	int num2 = val2 == 0 ? throw new DivideByZeroException() : 5 / val2;

위처럼 식으로 쓸 수 있다.<br/>


## finally
try 블록에서 예외가 던져지면 프로그램은 try의 나머지 부분을 무시하고 catch 절로 바로 뛰어넘는다.<br/>
try 블록에서 실행해야할 중요한 코드를 실행 못하면 버그를 만들 수 있다.<br/>
이 경우 finally 키워드를 이용해 해결할 수 있다.<br/>


	try
	{
	
	    // 예외를 검사할 구간
	}
	catch ( 예외_객체 )
	{
	
	    // 예외가 던져지고 예외_객체인 경우 받을 구간
	}
	finally
	{
	
	    // 예외가 발생해도 꼭 실행해야 할 구간
	}


try 에 return으로 해당 메소드를 탈출해도 finally 부분은 반드시 실행된다.<br/>
finally 안에서도 예외가 발생할 수 있다면 finally 구문 안에 try ~ catch 절을 사용하면 된다.<br/>